### ISSUE TITLE
Error in draw_weather

### ISSUE THREAD

**Issue by zvin** [balenalabs/inkyshot#27]
Using `Paris, France` as location.
It doesn't happen all the time, most of the time it works.

```
INFO:root:Retrieving weather forecast
INFO:root:Prepare the weather data for drawing
Traceback (most recent call last):
  File "/usr/app/update-display.py", line 274, in <module>
    img = draw_weather(weather, img, SCALE)
  File "/usr/app/update-display.py", line 107, in draw_weather
    time_of_day = 'd' if weather['symbol'].split('_')[1] == 'day' else 'n'
IndexError: list index out of range
```

**Comment by gelbal** [comment]
Thanks for the report Alexis. I saw this error today as well. I think I know the issue. I'll open a PR to fix it.
